services:
  postgres:
    image: postgres@sha256:4ec37d2a07a0067f176fdcc9d4bb633a5724d2cc4f892c7a2046d054bb6939e5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=converg
    volumes:
      - pg-volume:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: ["postgres", "-c", "log_min_duration_statement=250"]
    deploy:
      resources:
        limits:
          cpus: ${BD_CPU_LIMITATION:-0.000}
          memory: ${BD_RAM_LIMITATION:-16Gb}

volumes:
  pg-volume:
    driver: local
